from yabadaba.record import Record

from .File import File

class Software(Record):

    """
    Class for Material Core "software" fields
    """

    ########################## Basic metadata fields ##########################

    @property
    def style(self) -> str:
        """str: The record style"""
        return 'constituent'

    @property
    def modelroot(self) -> str:
        """str: The root element of the content"""
        return 'constituent'

    ####################### Define Values and attributes #######################

    def _init_values(self):
        """
        Method that defines the value objects for the Record.  This should
        call the super of this method, then use self._add_value to create new Value objects.
        Note that the order values are defined matters
        when build_model is called!!!
        """
        
        self._add_value('str', 'name', valuerequired=True,
                        description='The name of the software package.')
        self._add_value('str', 'version',
                        description='The version of the software package.')
        self._add_value('recordlist', 'file', recordclass=File,
                        description='Input or output file for the software package associated with the computation. This includes the input file used to perform the computation, associated data files, and output generated by the software package. Most important are input files to enable reproduction of the dataset.')

    @property
    def _defaultextensible(self) -> bool:
        """bool: Default value for extensible for this record class."""
        return True
    
    def add_file(self, **kwargs):
        """Adds a file to the record"""
        self.get_value('file').append(**kwargs)

    def file_df(self):
        """Generates a pandas DataFrame of the file information"""
        return self.get_value('file').metadata_df()